### ISSUE TITLE
[BUG] Health counter scales up with weight counter

### ISSUE THREAD

**Issue by ghost** [Treyo1928/TreysHealthText-Lethal-Company-Mod#1]
As the title says, the counter scales with the weight counter, kinda weird and a somewhat annoying kind of issue.

**Comment by ghost** [comment]
Another example
![image](https://github.com/Treyo1928/TreysHealthText-Lethal-Company-Mod/assets/91152433/a9ad0bdc-a942-4f48-b9fc-f1042fd1acea)

**Comment by Treyo1928** [comment]
I'll look into it right away, thanks for letting me know.

**Comment by ghost** [comment]
> I'll look into it right away, thanks for letting me know.

Awesome, thanks!!

**Comment by Treyo1928** [comment]
Just released a patch onto thunderstore. It should be version 1.1.0, it might take thunderstore about an hour or so to update the listing.
