### ISSUE TITLE
Initial loading screen error

### ISSUE THREAD

**Issue by Paradox75831004** [Treyo1928/TreysHealthText-Lethal-Company-Mod#2]
When you start without this mod (either with an assembly of mods or just with this one mod), the initial loading “online system” appears. If you turn on the mod, it freezes and the scene does not appear.
![TreysHealthText_bug (1)](https://github.com/Treyo1928/TreysHealthText-Lethal-Company-Mod/assets/72872478/f13e0999-410c-4d0a-aea8-fb5e68bde686)

**Comment by UnrealzMe** [comment]
Same here. "Systems Online" won't appear with this mod enabled. 
![Screenshot_2](https://github.com/Treyo1928/TreysHealthText-Lethal-Company-Mod/assets/107071252/a86fa012-0459-4c11-ad3b-064879924db3)

**Comment by Treyo1928** [comment]
Ok I seem to understand now. The original comment seemed a bit confusing but I think I see what you guys are saying. I'll be busy tomorrow and maybe the day after that but I'll start working on a patch whenever I can.

**Comment by UnrealzMe** [comment]
Thank you!

**Comment by Treyo1928** [comment]
Just released a new patch, version 1.3.1, it should fix the issue but if I missed it somehow, make sure to let me know.

If you find any more bugs, please feel free to open another issue.

Thank You!
