### ISSUE TITLE
Text Color not working

### ISSUE THREAD

**Issue by UnrealzMe** [Treyo1928/TreysHealthText-Lethal-Company-Mod#3]
Text color setting not working and the text remains white.

**Comment by Treyo1928** [comment]
> Text color setting not working and the text remains white.

Do you have any insight into what may be causing it or what may be unique about your situation? It is very difficult to find a bug that I don't know how to replicate. If you can, would you mind sending your TreysHealthText.cfg file?

**Comment by UnrealzMe** [comment]
Default text color settings (243.015, 100.47, 0) is not working because it's a wrong format. (243, 100, 0) works fine. and i just realized that I need to put spaces after commas for this to work. Sorry for bothering you.
