### ISSUE TITLE
Double Health Text

### ISSUE THREAD

**Issue by LumpyMilkTea** [Treyo1928/TreysHealthText-Lethal-Company-Mod#5]
The health text “HP 100” duplicates after V50.

**Comment by Treyo1928** [comment]
Can you provide more details? I'm having trouble replicating this issue. I'd like you to share a screenshot of the duplicated text and a list of the mods you're using

**Comment by Lunxara** [comment]
> Can you provide more details? I'm having trouble replicating this issue. I'd like you to share a screenshot of the duplicated text and a list of the mods you're using

If I had to guess they were pairing it with GI and forgot to turn off GI's HitPoints feature lol

**Comment by Lunxara** [comment]
Since it does it similar enough to cause some confusion

**Comment by Treyo1928** [comment]
> > Can you provide more details? I'm having trouble replicating this issue. I'd like you to share a screenshot of the duplicated text and a list of the mods you're using
> 
> If I had to guess they were pairing it with GI and forgot to turn off GI's HitPoints feature lol

Oh ok lol. Thanks for letting me know.
